connectIPVersion: v4
bootstrapDns:
  - upstream: https://root.hagezi.org/dns-query
    ips:
      - 188.34.161.210
  - upstream: https://wurzn.hagezi.org/dns-query
    ips:
      - 159.69.155.94
  - upstream: https://juuri.hagezi.org/dns-query
    ips:
      - 95.217.163.17
upstreams:
  strategy: random
  timeout: 1200ms
  groups:
    default:
      - https://root.hagezi.org/dns-query
      - https://wurzn.hagezi.org/dns-query
      - https://juuri.hagezi.org/dns-query
ports:
  http: 127.0.0.1:8053
caching:
  maxItemsCount: 32768
  prefetching: false
  cacheTimeNegative: 5m
log:
  level: warn
  format: text
  timestamp: true
  privacy: true